SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS COVID19;

CREATE DATABASE COVID19;
USE COVID19;


CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100),
    CPF VARCHAR(11),
    DATA_NASCIMENTO DATE,
    SEXO CHAR (1),
    TIPO_PESSOA VARCHAR (45),
    PRIMARY KEY (IDPESSOA)
);


CREATE TABLE VACINA (	
	IDVACINA INT NOT NULL AUTO_INCREMENT,
	PAIS_DE_ORIGEM VARCHAR (100),
    ESTAGIO_PESQUISA INT,
	DATA_INICIO_PESQUISA DATE,
    IDPESQUISADOR INT NOT NULL,
	FOREIGN KEY (IDPESQUISADOR) REFERENCES PESSOA (IDPESSOA),
	PRIMARY KEY (IDVACINA)
);

INSERT INTO PESSOA VALUES (NULL, 'LUCAS','08741624912','2000-04-21','M','PESQUISADOR');
INSERT INTO VACINA VALUES (NULL, 'BRASIL',1,'2010-04-21','1');

SELECT * FROM VACINA;
SELECT * FROM PESSOA;